name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

# Cancel previous runs for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '21' ]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up GraalVM CE ${{ matrix.java }}
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ matrix.java }}
        distribution: 'graalvm-community'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle (includes running tests)
      run: ./gradlew build --build-cache --scan
    
    - name: Test Report Summary
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: "**/build/test-results/**/*.xml"
        reporter: java-junit
        fail-on-error: false