name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '21' ]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up GraalVM CE ${{ matrix.java }}
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ matrix.java }}
        distribution: 'graalvm-community'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: build/test-results/test/*.xml
        reporter: java-junit
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: false